### ISSUE TITLE
Exception during Predict Spots on Google Colab

### ISSUE THREAD

**Issue by tischi** [elephant-track/elephant-server#3]
Hi @ksugar,

I tried the Google Colab variant for the server and when execution "Predict Spots" after "Reset Seg Model" I am getting this error server-side (I am copying everything, the error can be seen twice at the end):

```
Copy authtoken from https://dashboard.ngrok.com/auth
··········
SSH command: ssh -p10739 root@8.tcp.ngrok.io
Root password: qXzK8cOwvkWxdAcGZwM0
/app
unlink: cannot unlink '/var/run/supervisor.sock': No such file or directory
/usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2021-05-10 18:54:18,645 CRIT Supervisor running as root (no user in config file)
2021-05-10 18:54:18,645 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2021-05-10 18:54:18,663 INFO RPC interface 'supervisor' initialized
2021-05-10 18:54:18,664 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-05-10 18:54:18,664 INFO supervisord started with pid 9825
2021-05-10 18:54:19,666 INFO spawned: 'nginx' with pid 9828
2021-05-10 18:54:19,668 INFO spawned: 'sshd' with pid 9829
2021-05-10 18:54:19,671 INFO spawned: 'redis-server' with pid 9830
2021-05-10 18:54:19,673 INFO spawned: 'uwsgi' with pid 9831
2021-05-10 18:54:19,678 INFO spawned: 'rabbitmq-server' with pid 9832
9830:C 10 May 18:54:19.699 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
9830:C 10 May 18:54:19.699 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=9830, just started
9830:C 10 May 18:54:19.699 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
9830:M 10 May 18:54:19.701 * Running mode=standalone, port=6379.
9830:M 10 May 18:54:19.701 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
9830:M 10 May 18:54:19.702 # Server initialized
9830:M 10 May 18:54:19.702 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
9830:M 10 May 18:54:19.702 * Ready to accept connections
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
[uWSGI] getting INI configuration from /app/uwsgi.ini

;uWSGI instance configuration
[uwsgi]
uid = user
gid = user
ini = /etc/uwsgi/uwsgi.ini
ini = /app/uwsgi.ini
module = main
callable = app
cheaper = 2
processes = 16
socket = /tmp/uwsgi.sock
chown-socket = nginx:nginx
chmod-socket = 664
hook-master-start = unix_signal:15 gracefully_kill_them_all
need-app = true
die-on-term = true
show-config = true
;end of configuration

*** Starting uWSGI 2.0.18 (64bit) on [Mon May 10 18:54:19 2021] ***
compiled with version: 7.3.0 on 22 July 2019 16:35:30
os: Linux-4.19.112+ #1 SMP Thu Jul 23 08:00:38 PDT 2020
nodename: ec22e12c95df
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 3
setgid() to 1001
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x56240abec120
setgid() to 1001
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1239640 bytes (1210 KB) for 16 cores
*** Operational MODE: preforking ***
/rabbitmq.sh: 15: /rabbitmq.sh: /rabbitmq.sh: 5: /rabbitmq.sh: rabbitmqctl: not found
*** User 'user' with password 'user' completed. ***
*** Log in the WebUI at port 5672 (example: http:/localhost:5672) ***
/rabbitmq.sh: 7: /rabbitmq.sh: rabbitmqctl: not found
/rabbitmq.sh: 8: /rabbitmq.sh: rabbitmqctl: not found
rabbitmq-server: not found
2021-05-10 18:54:20,221 INFO exited: rabbitmq-server (exit status 0; not expected)
2021-05-10 18:54:21,222 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-10 18:54:21,222 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-10 18:54:21,222 INFO success: redis-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-10 18:54:21,222 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-10 18:54:21,224 INFO spawned: 'rabbitmq-server' with pid 9841
/rabbitmq.sh: 15: /rabbitmq.sh: rabbitmq-server: not found
/rabbitmq.sh: 5: /rabbitmq.sh: rabbitmqctl: not found
/rabbitmq.sh: 7: /rabbitmq.sh: rabbitmqctl: not found
/rabbitmq.sh: 8: /rabbitmq.sh: rabbitmqctl: not found
*** User 'user' with password 'user' completed. ***
*** Log in the WebUI at port 5672 (example: http:/localhost:5672) ***
2021-05-10 18:54:21,657 INFO exited: rabbitmq-server (exit status 0; not expected)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x56240abec120 pid: 9831 (default app)
setgid() to 1001
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9831)
spawned uWSGI worker 1 (pid: 9844, cores: 1)
spawned uWSGI worker 2 (pid: 9845, cores: 1)
running "unix_signal:15 gracefully_kill_them_all" (master-start)...
2021-05-10 18:54:24,379 INFO spawned: 'rabbitmq-server' with pid 9848
/rabbitmq.sh: 15: /rabbitmq.sh: /rabbitmq.sh: 5: /rabbitmq.sh: rabbitmqctl: not found
/rabbitmq.sh: 7: /rabbitmq.sh: rabbitmqctl: not found
*** User 'user' with password 'user' completed. ***
*** Log in the WebUI at port 5672 (example: http:/localhost:5672) ***
/rabbitmq.sh: 8: /rabbitmq.sh: rabbitmqctl: not found
rabbitmq-server: not found
2021-05-10 18:54:24,638 INFO exited: rabbitmq-server (exit status 0; not expected)
2021-05-10 18:54:27,644 INFO spawned: 'rabbitmq-server' with pid 9851
/rabbitmq.sh: 15: /rabbitmq.sh: rabbitmq-server: not found
/rabbitmq.sh: 5: /rabbitmq.sh: rabbitmqctl: not found
/rabbitmq.sh: 7: /rabbitmq.sh: rabbitmqctl: not found
/rabbitmq.sh: 8: /rabbitmq.sh: rabbitmqctl: not found
*** User 'user' with password 'user' completed. ***
*** Log in the WebUI at port 5672 (example: http:/localhost:5672) ***
2021-05-10 18:54:27,913 INFO exited: rabbitmq-server (exit status 0; not expected)
2021-05-10 18:54:28,914 INFO gave up: rabbitmq-server entered FATAL state, too many start retries too quickly
[params updated] lr: 5e-05, n_crops: 3
[pid: 9844|app: 0|req: 1/1] 127.0.0.1 () {40 vars in 509 bytes} [Mon May 10 18:57:11 2021] POST /params => generated 40 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
127.0.0.1 - - [10/May/2021:18:57:11 +0000] "POST /params HTTP/1.1" 200 40 "-" "unirest-java/3.1.00" "-"
[params updated] lr: 5e-05, n_crops: 3
[pid: 9844|app: 0|req: 2/2] 127.0.0.1 () {40 vars in 509 bytes} [Mon May 10 18:57:41 2021] POST /params => generated 40 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
127.0.0.1 - - [10/May/2021:18:57:41 +0000] "POST /params HTTP/1.1" 200 40 "-" "unirest-java/3.1.00" "-"
GPU is available
auto_bg_thresh: None
c_ratio: None
class_weights: (1.0, 10.0, 10.0)
crop_box: None
crop_size: (16, 384, 384)
dataset_name: elephant-demo
debug: False
device: cuda
false_weight: None
is_livemode: False
is_pad: False
lr: None
n_crops: None
n_epochs: None
output_prediction: False
p_thresh: None
patch_size: None
r_max: None
r_min: None
rotation_angle: None
scale_factor_base: None
timepoint: None
use_median: None
zpath_input: /workspace/datasets/elephant-demo/imgs.zarr
zpath_seg_label: /workspace/datasets/elephant-demo/seg_labels.zarr
zpath_seg_label_vis: /workspace/datasets/elephant-demo/seg_labels_vis.zarr
zpath_seg_output: /workspace/datasets/elephant-demo/seg_outputs.zarr
[pid: 9844|app: 0|req: 3/3] 127.0.0.1 () {40 vars in 517 bytes} [Mon May 10 18:58:09 2021] POST /update/seg => generated 19 bytes in 45 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
127.0.0.1 - - [10/May/2021:18:58:09 +0000] "POST /update/seg HTTP/1.1" 200 19 "-" "unirest-java/3.1.00" "-"
[params updated] lr: 5e-05, n_crops: 3
127.0.0.1 - - [10/May/2021:19:00:45 +0000] "POST /params HTTP/1.1" 200 40 "-" "unirest-java/3.1.00" "-"
[pid: 9844|app: 0|req: 4/4] 127.0.0.1 () {40 vars in 509 bytes} [Mon May 10 19:00:45 2021] POST /params => generated 40 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
GPU is available
c_ratio: 0.3
crop_box: None
crop_size: (16, 384, 384)
dataset_name: elephant-demo
debug: False
device: cuda
is_pad: True
keep_axials: (True, True, True, False)
model_path: /workspace/models/seg.pth
output_prediction: False
p_thresh: 0.3
patch_size: None
r_max: 5
r_min: 1
scales: [2.48, 0.3119629, 0.3119629]
timepoint: 0
use_median: False
zpath_input: /workspace/datasets/elephant-demo/imgs.zarr
zpath_seg_output: /workspace/datasets/elephant-demo/seg_outputs.zarr
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/elephant/common.py", line 377, in detect_spots
    config.is_pad)
  File "/usr/local/lib/python3.7/site-packages/elephant/common.py", line 310, in _get_seg_prediction
    device, is_eval=True, is_pad=is_pad)
  File "/usr/local/lib/python3.7/site-packages/elephant/models.py", line 313, in load_seg_models
    checkpoint = torch.load(model_path)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/models/seg.pth'

Traceback (most recent call last):
  File "./main.py", line 631, in predict_seg
    spots = detect_spots(config)
  File "/usr/local/lib/python3.7/site-packages/elephant/common.py", line 386, in detect_spots
    prediction[-1],  # last channel is the center label
UnboundLocalError: local variable 'prediction' referenced before assignment

[pid: 9844|app: 0|req: 5/5] 127.0.0.1 () {40 vars in 521 bytes} [Mon May 10 19:01:57 2021] POST /predict/seg => generated 80 bytes in 78 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
127.0.0.1 - - [10/May/2021:19:01:57 +0000] "POST /predict/seg HTTP/1.1" 500 80 "-" "unirest-java/3.1.00" "-"
GPU is available
crop_size: [16, 128, 128]
dataset_name: elephant-demo
debug: False
device: cuda
keep_axials: (True, True, True, False)
model_path: /workspace/models/seg.pth
n_crops: 3
n_models: 1
output_prediction: False
patch_size: None
scales: [2.48, 0.3119629, 0.3119629]
timepoint: None
zpath_input: /workspace/datasets/elephant-demo/imgs.zarr
Train Epoch: 0 [0/3 (0%)]	Loss: 0.944061
Train Epoch: 0 [1/3 (33%)]	Loss: 0.820469
Train Epoch: 0 [2/3 (67%)]	Loss: 0.906118
Train Epoch: 1 [0/3 (0%)]	Loss: 0.717266
Train Epoch: 1 [1/3 (33%)]	Loss: 0.610715
Train Epoch: 1 [2/3 (67%)]	Loss: 0.616530
Train Epoch: 2 [0/3 (0%)]	Loss: 0.534876
Train Epoch: 2 [1/3 (33%)]	Loss: 0.527995
Train Epoch: 2 [2/3 (67%)]	Loss: 0.520349
[pid: 9844|app: 0|req: 6/6] 127.0.0.1 () {40 vars in 517 bytes} [Mon May 10 19:03:41 2021] POST /reset/seg => generated 19 bytes in 8055 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
127.0.0.1 - - [10/May/2021:19:03:49 +0000] "POST /reset/seg HTTP/1.1" 200 19 "-" "unirest-java/3.1.00" "-"
GPU is available
c_ratio: 0.3
crop_box: None
crop_size: (16, 384, 384)
dataset_name: elephant-demo
debug: False
device: cuda
is_pad: True
keep_axials: (True, True, True, False)
model_path: /workspace/models/seg.pth
output_prediction: False
p_thresh: 0.3
patch_size: None
r_max: 5
r_min: 1
scales: [2.48, 0.3119629, 0.3119629]
timepoint: 0
use_median: False
zpath_input: /workspace/datasets/elephant-demo/imgs.zarr
zpath_seg_output: /workspace/datasets/elephant-demo/seg_outputs.zarr
skip a spot with invalid eigen value(s): [-1.83502765e-17  1.51687318e-01  3.08751634e+00]
skip a spot with invalid eigen value(s): [-5.52155015e-19  4.68791110e-02  6.12873904e+00]
skip a spot with invalid eigen value(s): [-1.38777878e-17  8.52286896e-18  3.56908596e+00]
skip a spot with invalid eigen value(s): [-2.10190679e-17  6.50629416e-02  3.17414071e+00]
skip a spot with invalid eigen value(s): [-2.08166817e-17  7.29906382e-02  3.09953021e+00]
skip a spot with invalid eigen value(s): [-1.38777878e-17  8.52286896e-18  3.56908596e+00]
skip a spot with invalid eigen value(s): [-2.24773690e-17  8.16898002e-18  3.51434298e+00]
skip a spot with invalid eigen value(s): [-1.38777878e-17  8.52286896e-18  3.56908596e+00]
skip a spot with invalid eigen value(s): [-2.24773690e-17  8.16898002e-18  3.51434298e+00]
Traceback (most recent call last):
  File "./main.py", line 632, in predict_seg
    get_mq_connection().channel().basic_publish(
  File "./main.py", line 104, in get_mq_connection
    pika.ConnectionParameters(host='localhost', heartbeat=0))
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError

[pid: 9844|app: 0|req: 7/7] 127.0.0.1 () {40 vars in 521 bytes} [Mon May 10 19:05:43 2021] POST /predict/seg => generated 24 bytes in 2249 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
127.0.0.1 - - [10/May/2021:19:05:45 +0000] "POST /predict/seg HTTP/1.1" 500 24 "-" "unirest-java/3.1.00" "-"
[params updated] lr: 5e-05, n_crops: 3
127.0.0.1 - - [10/May/2021:19:07:44 +0000] "POST /params HTTP/1.1" 200 40 "-" "unirest-java/3.1.00" "-"
[pid: 9844|app: 0|req: 8/8] 127.0.0.1 () {40 vars in 509 bytes} [Mon May 10 19:07:44 2021] POST /params => generated 40 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
GPU is available
c_ratio: 0.3
crop_box: None
crop_size: (16, 384, 384)
dataset_name: elephant-demo
debug: False
device: cuda
is_pad: True
keep_axials: (True, True, True, False)
model_path: /workspace/models/seg.pth
output_prediction: False
p_thresh: 0.3
patch_size: None
r_max: 5
r_min: 1
scales: [2.48, 0.3119629, 0.3119629]
timepoint: 0
use_median: False
zpath_input: /workspace/datasets/elephant-demo/imgs.zarr
zpath_seg_output: /workspace/datasets/elephant-demo/seg_outputs.zarr
skip a spot with invalid eigen value(s): [-1.83502765e-17  1.51687318e-01  3.08751634e+00]
skip a spot with invalid eigen value(s): [-5.52155015e-19  4.68791110e-02  6.12873904e+00]
skip a spot with invalid eigen value(s): [-1.38777878e-17  8.52286896e-18  3.56908596e+00]
skip a spot with invalid eigen value(s): [-2.10190679e-17  6.50629416e-02  3.17414071e+00]
skip a spot with invalid eigen value(s): [-2.08166817e-17  7.29906382e-02  3.09953021e+00]
skip a spot with invalid eigen value(s): [-1.38777878e-17  8.52286896e-18  3.56908596e+00]
skip a spot with invalid eigen value(s): [-2.24773690e-17  8.16898002e-18  3.51434298e+00]
skip a spot with invalid eigen value(s): [-1.38777878e-17  8.52286896e-18  3.56908596e+00]
skip a spot with invalid eigen value(s): [-2.24773690e-17  8.16898002e-18  3.51434298e+00]
Traceback (most recent call last):
  File "./main.py", line 632, in predict_seg
    get_mq_connection().channel().basic_publish(
  File "./main.py", line 104, in get_mq_connection
    pika.ConnectionParameters(host='localhost', heartbeat=0))
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError

[pid: 9844|app: 0|req: 9/9] 127.0.0.1 () {40 vars in 521 bytes} [Mon May 10 19:08:51 2021] POST /predict/seg => generated 24 bytes in 2104 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
127.0.0.1 - - [10/May/2021:19:08:53 +0000] "POST /predict/seg HTTP/1.1" 500 24 "-" "unirest-java/3.1.00" "-"
GPU is available
crop_size: [16, 128, 128]
dataset_name: elephant-demo
debug: False
device: cuda
keep_axials: (True, True, True, False)
model_path: /workspace/models/seg.pth
n_crops: 3
n_models: 1
output_prediction: False
patch_size: None
scales: [2.48, 0.3119629, 0.3119629]
timepoint: None
zpath_input: /workspace/datasets/elephant-demo/imgs.zarr
Train Epoch: 0 [0/3 (0%)]	Loss: 0.826745
Train Epoch: 0 [1/3 (33%)]	Loss: 0.681950
Train Epoch: 0 [2/3 (67%)]	Loss: 0.537833
Train Epoch: 1 [0/3 (0%)]	Loss: 0.451315
Train Epoch: 1 [1/3 (33%)]	Loss: 0.412080
Train Epoch: 1 [2/3 (67%)]	Loss: 0.410014
Train Epoch: 2 [0/3 (0%)]	Loss: 0.370644
Train Epoch: 2 [1/3 (33%)]	Loss: 0.375605
Train Epoch: 2 [2/3 (67%)]	Loss: 0.398046
[pid: 9844|app: 0|req: 10/10] 127.0.0.1 () {40 vars in 517 bytes} [Mon May 10 19:09:50 2021] POST /reset/seg => generated 19 bytes in 6481 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
127.0.0.1 - - [10/May/2021:19:09:56 +0000] "POST /reset/seg HTTP/1.1" 200 19 "-" "unirest-java/3.1.00" "-"
GPU is available
c_ratio: 0.3
crop_box: None
crop_size: (16, 384, 384)
dataset_name: elephant-demo
debug: False
device: cuda
is_pad: True
keep_axials: (True, True, True, False)
model_path: /workspace/models/seg.pth
output_prediction: False
p_thresh: 0.3
patch_size: None
r_max: 5
r_min: 1
scales: [2.48, 0.3119629, 0.3119629]
timepoint: 0
use_median: False
zpath_input: /workspace/datasets/elephant-demo/imgs.zarr
zpath_seg_output: /workspace/datasets/elephant-demo/seg_outputs.zarr
Traceback (most recent call last):
  File "./main.py", line 632, in predict_seg
    get_mq_connection().channel().basic_publish(
  File "./main.py", line 104, in get_mq_connection
    pika.ConnectionParameters(host='localhost', heartbeat=0))
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError

[pid: 9844|app: 0|req: 11/11] 127.0.0.1 () {40 vars in 521 bytes} [Mon May 10 19:10:30 2021] POST /predict/seg => generated 24 bytes in 1830 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
127.0.0.1 - - [10/May/2021:19:10:32 +0000] "POST /predict/seg HTTP/1.1" 500 24 "-" "unirest-java/3.1.00" "-"
```

Here are my server settings within Mastodon:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/2157566/117712419-97080380-b1d4-11eb-80c1-bb771de20dbb.png">

Do I maybe have to change them?

**Comment by ksugar** [comment]
Hi @tischi,

thank you for reporting this issue.
It seems that the installation step for RabbitMQ using Bintray is outdated. I updated it following [the latest instructions](https://www.rabbitmq.com/install-debian.html#apt-quick-start-cloudsmith).
Please try it again with the latest Colab notebook.
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/elephant-track/elephant-server/blob/main/elephant_server.ipynb)

Independent of this issue, it is possible that you have no outputs (ellipsoids) after prediction in the very beginning phase.
In that case, please keep training for several iterations or decrease the `probablility threshold` parameter from the settings on the client.

**Comment by tischi** [comment]
Works now!
Thanks for the fast fix!
